import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Card from "@/components/card";

export default function Home() {
  const arr = [1, 2, 3, 4, 5,6,7,8,9,10,11,12,13,14];
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {arr.map(item => <Card key={item}>{item}</Card>)}
      </main>
    </>
  );
}
